### ISSUE TITLE
Status bar issues 

### ISSUE THREAD

**Issue by logeshwywan** [midnightchip/HomeGesture-Full#2]
1. IPhone X status bar not showing in all apps, only showed in home screen 
2. Status bar not showing in control center 
3. Press home button for Siri not working 

Eventhough I have enabled these settings, it didn't work out!

I'm @ ios 11 with SE

**Comment by PINPAL** [comment]
Can you post your tweaklist? Which build are you running? The latest 2.0.0 from Dynastic Repo? Did you respring after applying the settings?

**Comment by logeshwywan** [comment]
Helo,
  

  
Here's my tweak list,
  

  
  
  applist
  
  apt7
  
  apt7-key
  
  apt7-lib
  
  base
  
  bash
  
  berkeleydb
  
  bzip2
  
  ca.kirara.voltage
  
  com.a3tweaks.flipswitch
  
  com.creaturecoding.libcspreferences
  
  com.creaturesurvive.libcscolorpicker
  
  com.ex.libsubstitute
  
  com.f0u4d.watusitools
  
  com.fouadraheb.watusi
  
  com.hackyouriphone.audiorecorder2
  
  com.iarrays.libiarrays
  
  com.iarrays.whoozit
  
  com.imkpatil.letmeknow
  
  com.julioverne.ntspeed
  
  com.justinpetkovic.youtubetools
  
  com.level3tjg.ipapatcher
  
  com.linusyang.localeutf8
  
  com.modmyi.libswift4
  
  com.muirey03.silentair
  
  com.opa334.safariplus
  
  com.pazkachlon.berry
  
  com.ps.emojiportwt
  
  com.purdix.muze4
  
  com.reddoorendeavors.3edgy5me
  
  com.repo.xarold.com.cracktool3
  
  com.repo.xarold.com.cydown
  
  com.repo.xarold.com.inapp
  
  com.repo.xarold.com.notepad
  
  com.repo.xarold.com.reprovision
  
  com.repo.xarold.com.stackxi
  
  com.rishanan.springplus11
  
  com.rpetrich.rocketbootstrap
  
  com.spark.libsparkapplist
  
  com.spark.snowboard
  
  com.synnyg.backupaz3
  
  com.thireus.untrustedhostsblocker9
  
  com.tigisoftware.filza
  
  com.vitataf.homegesture
  
  com.zyoxdesigns.offwhite
  
  coreutils
  
  coreutils-bin
  
  cydia
  
  cydia-gui
  
  cydia-lproj
  
  darwintools
  
  debianutils
  
  diffutils
  
  dpkg
  
  findutils
  
  firmware
  
  firmware-sbin
  
  gawk
  
  gnupg
  
  grep
  
  gzip
  
  iosgods.com.asphalt9
  
  jp.ashikase.libpackageinfo
  
  jp.ashikase.techsupport
  
  ldid
  
  libactivator
  
  lzma
  
  mobilesubstrate
  
  ncurses
  
  net.angelxwind.appsyncunified
  
  net.limneos.libbulletin
  
  openssh
  
  openssl
  
  org.coolstar.cctools
  
  org.coolstar.ld64
  
  org.coolstar.tweakinject
  
  org.thebigboss.exkeyboard
  
  org.thebigboss.libcolorpicker
  
  org.thebigboss.repo.icons
  
  p7zip
  
  preferenceloader
  
  profile.d
  
  sed
  
  shell-cmds
  
  system-cmds
  
  tar
  
  uikittools
  
  unrar
  
  unzip
  
  uuid
  
  ws.hbang.common
  
  ws.hbang.newterm2
  
  xyz.xninja.systeminfo
  
  zip
  

  
And I'm using latest build     2.0.0 from Dynastic Repo then I have respring after apply the settings !
  
  
  
 Thanks,
  
 Logesh   
  
 +91 9710090976   
  
  

  
  

  
  
>

**Comment by logeshwywan** [comment]
Is there any update regarding this?
  

  
  

  
  
>

**Comment by logeshwywan** [comment]
Awaiting for your kind reply!

Kind Regards,
Logesh
9710090976 ( tel:9710090976 )

**Comment by PINPAL** [comment]
The status bar in apps will be fixed in the next update. As for the other things, these are conflicts with your tweaks. I suggest you begin testing conflicts by removing pirated tweaks.

**Comment by logeshwywan** [comment]
After I have remove all tweaks with delectra script even though issues persists!

Kind Regards,
Logesh
9710090976 ( tel:9710090976 )
