### ISSUE TITLE
Screenshot not eorking

### ISSUE THREAD

**Issue by grega1303** [midnightchip/HomeGesture-Full#32]
On iPhone se 12.1.1 I can not take a screenshot whit homegesture installed

**Comment by dahshd** [comment]
You have to change it under the hardware button settings. On iPhone X you screenshot with volume up and the power button

**Comment by grega1303** [comment]
Volume up and power button does not work. And home and lock does not work. Here is a link to all my tweaks in the form of a YouTube video because I can not take screen shots. https://youtu.be/tHOjRoGfstg

**Comment by IziGlizi** [comment]
Same thing. iPhone SE iOS 12.1.1 beta 3.
