### ISSUE TITLE
Swipe up to unlock at lockscreen

### ISSUE THREAD

**Issue by ios11iphone6s** [midnightchip/HomeGesture-Full#4]
#1 Slow animation, please speed it up for best realistic experience.

#2 carrier hide on statusbar, it’s only hides on lockscreen & homescreen , not hides in 
stock app like settings.app etc

#3 homebar is overlapping dots at 
lockscreen

**Comment by PINPAL** [comment]
#1 What do you mean? It's exactly like the iPhone X

#2 This is already fixed. Compile from source.

#3 Turn off page dots. The iPhone X does not have page dots and therefore it will overlap (You can disable these in the lockscreen settings of HomeGesture.
