### ISSUE TITLE
Issue w/ iPX status bar on in certain apps

### ISSUE THREAD

**Issue by iDiddy** [midnightchip/HomeGesture-Full#42]
On Instagram and Twitter, having the iPX Status Bar on will mess create some issues.
On Instragam, it pushed the top section where it says “Instragram” down so it overlaps over the stories a little bit, and on Twitter the profile picture will overlap with the status bar. 

Photos: http://imgur.com/pJXFAi3
http://imgur.com/yPtRMA3 

Device Info: iPhone10,4 iOS 12.1.1 b3

**Comment by eezwanlee** [comment]
What is the fix? Having the same problem.
