### ISSUE TITLE
just saying

### ISSUE THREAD

**Issue by Pipboy911** [midnightchip/HomeGesture-Full#54]
You should make an option to disable reachability too
Then your tweak is perfect

**Comment by midnightchip** [comment]
Thats an option in settings, Im merging a change from Neptune to move reachablility down

**Comment by Pipboy911** [comment]
im using SE so it doesn't have that option in the settings
but when i install homegesture i suddenly have reachability

**Comment by PINPAL** [comment]
Does it work with regular double tapping TouchID?

**Comment by Pipboy911** [comment]
yes

**Comment by Pipboy911** [comment]
I can still do it with new update

**Comment by imReker** [comment]
> Thats an option in settings, Im merging a change from Neptune to move reachablility down

Same problem here, and can't find reachablility option too @midnightchip
