### ISSUE TITLE
Status Bar temporarily being in iPad style when “iPhone X” style is disabled upon closing control centre view

### ISSUE THREAD

**Issue by JQ555888** [midnightchip/HomeGesture-Full#68]
When closing control centre, there’s a temporary lag on the status bar being in the iPad style instead of normal when both “iPhone X” and “iPad” style options are actually disabled.

**Comment by JQ555888** [comment]
I’m on version 2.1.4 downloaded from Dynastic repo.

**Comment by PINPAL** [comment]
Known bug. I’m currently working on fixing this but it’s definitely not an easy solution.

**Comment by binksxela** [comment]
That’s weird because Neptune doesn’t have this issue

**Comment by 70599** [comment]
Same issue on my iPhone SE iOS 12.1.2.

**Comment by ghost** [comment]
Use LittleXS it fixes that.
