### ISSUE TITLE
Dock isn't transparent

### ISSUE THREAD

**Issue by obsidianrepo** [midnightchip/HomeGesture-Full#71]
I have transparent dock turned on in every tweak possible of doing this, including HomeGesture, but the background blur still shows up. This is the reason why I can't stand HomeGesture, I want a transparent dock. Why doesn't this work?

**Comment by PINPAL** [comment]
HomeGesture doesn’t currently have a clear dock feature. But if your using the rounded dock you will need an iPhone X compatible tweak. You can try ClearDock.
