### ISSUE TITLE
[Wish] Change height and hide icons of X status bar

### ISSUE THREAD

**Issue by csuka** [midnightchip/HomeGesture-Full#77]
Hi,

I'm using HomeGesture 2.1.4. on my iPhone 6S.

I'd like to request the following:

1. Hide icons, such as the services bar and the location services
2. Place the time in the center, instead of aligned left
3. Place the status bar more at the top, now there is some space between the top and the status bar.

Image to clarify: https://imgur.com/a/FFrVaCk

Is this possible? I'm using HomeGesture because the tweak Xeon depends on this tweak.

**Comment by PINPAL** [comment]
Disable iPhone X status bar and use Zeppelin rather than Xeon. Xeon is for iPhone X devices only.
