### ISSUE TITLE
Cc and status bar animation glitch

### ISSUE THREAD

**Issue by manzox3** [midnightchip/HomeGesture-Full#8]
When I pull down the cc it shows the the status bar but when I slide it back up the right side of the status bar ( the WiFi and battery icon ) go off the screen for a second or 2 then come back down to normal level

**Comment by yex101** [comment]
This happens to me aswell

**Comment by yex101** [comment]
iPhone 7 Plus 12.1.1

**Comment by abn5x** [comment]
happens to me aswell iphone se

**Comment by jbbanks19** [comment]
Happens to me, but repacked WiFi and data bars with date and time for a few seconds.
