### ISSUE TITLE
Doesn’t work with Lithium Ion

### ISSUE THREAD

**Issue by Ragnarok96** [midnightchip/HomeGesture-Full#80]
I am using lithium ion for custom battery indicators but if I turn on iPhone X status bar or iPad status bar it still uses the default stock battery icon

**Comment by PINPAL** [comment]
Lithium Ion isn’t compatible with the iPhone X or iPad on iOS 12. Your going to need to find an alternative tweak that’s compatible with iPhone X for theming the battery.

**Comment by Ragnarok96** [comment]
I don’t have an iPhone X, I am using an iPhone 6S - Lithium Ion does work but stops working when I turn on iPad style status bar in your tweak or the iPhone X style one.

Sent from my iPhone

On 4 Apr 2019, at 14:09, PINPAL <notifications@github.com<mailto:notifications@github.com>> wrote:

Lithium Ion isn’t compatible with the iPhone X or iPad on iOS 12. Your going to need to find an alternative tweak that’s compatible with iPhone X for theming the battery.

**Comment by PINPAL** [comment]
Yes it enables the iPhone X status bar which means you must find a tweak compatible with the iPhone X despite your device.
