### ISSUE TITLE
Control Center toggles don't work instantly.

### ISSUE THREAD

**Issue by sambuzzlight** [midnightchip/HomeGesture-Full#9]
If you pull down the NC and try to interact with the toggles there is a 2-3 second delay in doing so. I had this issue on my iPhone SE on 11.3.1 with older versions of Homegesture but it was fixed in 2.0.0. Current device: iPhone 7, 12.1.1. 

P.S Sorry this is my first time reporting an issue on Github so format might seem weird and also a HUGE fan of your work! :)

**Comment by dahshd** [comment]
Bro, it’s probably because you have the AnimationsBeFast tweak and toggled the function “Enable touch when animating” off, you have to toggle it on. I had the exact same issue and this fixed it

**Comment by sambuzzlight** [comment]
> Bro, it’s probably because you have the AnimationsBeFast tweak and toggled the function “Enable touch when animating” off, you have to toggle it on. I had the exact same issue and this fixed it

You are right, i found out by contacting the dev of AnimationsBeFast a week ago, thanks nonetheless!
