### ISSUE TITLE
hey！not working on IOS13

### ISSUE THREAD

**Issue by biankobe24** [midnightchip/HomeGesture-Full#99]
plz,update this!i need it gesture!

**Comment by hasanbasri1993** [comment]
Yes... 
please update to 13 

Thanks.

**Comment by PINPAL** [comment]
Unfortunately I do not own a device new enough to support iOS 13 and Midnight is currently away on a very long trip.

Sorry but I have no way of being able to update it at the moment.

**Comment by star0077** [comment]
Hello, my dear friend, may you update your tweak for iOS 13? It’s best tweak

**Comment by PINPAL** [comment]
Hi,

I currently have no jail broken devices on iOS 13 and so am not able to support the tweak.
Midnight is also away at the moment any won’t be back for a long time.

Sorry about that.

**Comment by star0077** [comment]
I understood you, it is a pity



Отправлено из мобильной Почты Mail.ru


суббота, 29 февраля 2020 г., 22:04 +0800 от notifications@github.com  <notifications@github.com>:
>Hi,
>
>I currently have no jail broken devices on iOS 13 and so am not able to support the tweak.
>Midnight is also away at the moment any won’t be back for a long time.
>
>Sorry about that.
>

**Comment by star0077** [comment]
Have a good day 



Отправлено из мобильной Почты Mail.ru


суббота, 29 февраля 2020 г., 22:04 +0800 от notifications@github.com  <notifications@github.com>:
>Hi,
>
>I currently have no jail broken devices on iOS 13 and so am not able to support the tweak.
>Midnight is also away at the moment any won’t be back for a long time.
>
>Sorry about that.
>

**Comment by biankobe24** [comment]
> Hi, I currently have no jail broken devices on iOS 13 and so am not able to support the tweak. Midnight is also away at the moment any won’t be back for a long time. Sorry about that.
> […](#)
> On 29 Feb 2020, at 4:56 am, star0077 ***@***.***> wrote: ﻿ Hello, my dear friend, may you update your tweak for iOS 13? It’s best tweak — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

ok，thanks，have a nice trip

**Comment by aliakrum** [comment]
Please update your home gesture for ios 13.5 , i m using 6s and unable tou use my favorite tweak , please do something for us

**Comment by benjitusk** [comment]
Hello, wonderful developers. I am having similar issues, and am willing to volunteer to test out .debs if needed (@PINPAL). Thank you for all the hard word you put into your tweaks!
